version: "3"
services:
  ansible:
    image: ansible
    hostname: ansible
    container_name: ansible
    volumes:
      - ./:/root
    ports:
      - "8888:8888"
    command: bash -c "sleep 10 && service ssh start && jupyter notebook --notebook-dir=/root/ --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token=''"
  debian:
    image: ansible
    hostname: debian
    container_name: debian
    volumes:
      - ./:/root
  hdp:
    image: hortonworks/ambari-server
    hostname: hdp
    volumes:
      - ./:/data

